### ISSUE TITLE
Allow add-on downgrade from repository

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/repository.castagnait#11]
For now, the repository only shows the last version for install or upgrade.

It would be convenient if we could downgrade too 

The repo should also propose at least 0.14.6 that was pretty stable.

**Comment by CastagnaIT** [comment]
@notoco Have you ever tried adding multiple versions of the same addon in addons.xml?
I've just done a test keeping also the previous version, but Kodi does not propose both versions
Do you have any ideas?

**Comment by CastagnaIT** [comment]
rollback seems to work, but i don't understand why when i update addons.xml, Kodi doesn't seem to notice the changes at first glance...
