### ISSUE TITLE
Background services may not be available

### ISSUE THREAD

**Issue by Tokn59** [CastagnaIT/repository.castagnait#13]
Hello,

Installed the repository on my OSMC (Latest version 11/2019). From the newly installed repository I installed the Netflix plugin. When starting Netflix (or trying to configure) I get the following error :

Background services may not be available. 

Waited, rebooted ... Error remains. 

Anything I did wrong ?

Many thanks for making this available to the community !!!

Kind Regards,

Tony

**Comment by CastagnaIT** [comment]
this is the release repository not add-on repo
