### ISSUE TITLE
Library sync

### ISSUE THREAD

**Issue by JohnyJack01** [CastagnaIT/repository.castagnait#14]
So I installed and tested, and everything is working (good work!) except that I cannot sync Netflix´s My List with Kodi´s library. I tried many times with various settings (full sync, update, custom library location, etc.) and the addon seems to be syncing all the items in My list (at least progress for every item bar is being shown during syncing) but when I check the library in Kodi it is empty (there is no other source in the library). I use Netflix family account.
Kodi release: 18.2 installed on top of Raspbian

Any idea what am I doing wrong?

**Comment by CastagnaIT** [comment]
This is the repository for the releases, not the addon repository

How to here: https://github.com/CastagnaIT/plugin.video.netflix/wiki/How-to-export-and-sync-tv-shows-and-movies-in-Kodi-library

for questions of all kinds use Kodi forum
for addon errors/problems go to https://github.com/CastagnaIT/plugin.video.netflix/
