### ISSUE TITLE
Failing to connect to Repo after installation by ZIP

### ISSUE THREAD

**Issue by Bracketmounts** [CastagnaIT/repository.castagnait#17]
Followed installation guidelines from the plugin Wiki and after successful installation of the repo, Attempting to install an addon from the repo version 1.0.1 or version 1.0.0 causes an error stating "Could Not connect to the repository."

- Have confirmed internet connection. 
- Can download ZIP file. 
- Can install other addons from other repos.
- Can get to path https://github.com/CastagnaIT/repository.castagnait/raw/master/addons.xml via web browser on the TV box

**Hardware and Software**
- OS: Android 7.12
- Hardware: Tanix TX9 Pro TV Box. http://www.tanix-box.com/project-view/tanix-tx9-tv-box-amlogic-s912-android-7-1/
- Kodi Versions: 18.4 and 18.5

**Comment by CastagnaIT** [comment]
from repo side all is working
so the problem is in your device or network
