### ISSUE TITLE
Please keep old versions in the repo

### ISSUE THREAD

**Issue by seanrand** [CastagnaIT/repository.castagnait#2]
Keeping old versions in the addons.xml (and zips in the repo) would allow us to downgrade/choose a version to use.

For example right now, my addon auto-updated to 0.14.2, and everything broke. I'd like to revert to the previous version until I figure out what happened, but I can't do that via Kodi's addon update/select version dialogue, I have to install the previous version zip manually.

**Comment by CastagnaIT** [comment]
old versions are all kept in the list but kodi does not display old versions, ask in the kodi forum if there is a way to view them

**Comment by seanrand** [comment]
Okay let me try this again, this isn't a Kodi issue.

As far as I can tell, the addons.xml only contains one entry for the Netflix plugin and one entry for this repo.

What I'm suggesting is to _add_  an entry for each new version instead of _replacing_  the previous one. That way the old versions will still show up in the kodi updater/version selector.
