### ISSUE TITLE
[Request] Make available as a Kodi File Manager source

### ISSUE THREAD

**Issue by finkleandeinhorn** [CastagnaIT/repository.castagnait#3]
With there already being an `index.html` file present, all it would take to make the repo show up inside Kodi's File Manager would be to [enable GitHub Pages](https://pages.github.com/)... Any possibility of this?

**Comment by drinfernoo** [comment]
Any idea if this will ever be addressed?

**Comment by CastagnaIT** [comment]
I don't think what you mean for "Kodi's File Manager", however enable github page did not work it says i need to generate more pages, i'm not interested in further complicating things for nothing,
but if you have a full working example i can try to see how it works

**Comment by finkleandeinhorn** [comment]
There are loads of working examples... any Kodi source of the form `https://xxxxx.github.io/` or similar is using GitHub Pages for easy installation inside Kodi.

**Comment by drinfernoo** [comment]
By enabling GitHub Pages on this repository, it would allow users to install the repo `.zip` inside Kodi, by adding https://castagnait.github.io/repository.castagnait/ as a file source.

**Comment by SerpentDrago** [comment]
Looks like you have everything you need already with the index.html and repo zips in the main folder for  the above url by dr to work . 

you just need to enable github pages for this repo

**Comment by CastagnaIT** [comment]
Done!
