### ISSUE TITLE
Can't login LibreElec 9.02 + Kodi 18 Leia + Default skin

### ISSUE THREAD

**Issue by Friesenhahn** [CastagnaIT/repository.castagnait#5]
I installed the addon via the repository in version 0.14.5 

Until more or less a week ago everything worked pretty great. Then I do not know if it was right after updating to version 0.14.6 (went automatically) I could no longer watch anything. Still I was logged in and could browse all the lists and movies though initially when starting the addon it said to check my credentials. I uninstalled the addon and removed all settings. Then I reinstalled everything but no luck and now I am not even able to login though I am pretty sure the credentials are fine.

Which logfile do you want me to upload? I am still somehow new to Kodi and not well aware of everything. Any help would be very much appreciated as I greatly enjoyed watching Netflix on my Kodi-HTPC.

Thanks in advance and keep up the great work!

**Comment by CastagnaIT** [comment]
open the "issue" in the plugin repository, follow the rules written in the issue guideline, the log file needed is kodi.log
