### ISSUE TITLE
Subtitle and audio options problem

### ISSUE THREAD

**Issue by Gufersil** [CastagnaIT/repository.castagnait#6]
There are no subtitles options to choose on the tv shows and series. And there is no portuguese brazil in audio options, but it's available on netflix web and android/IOS apps.

**Comment by marcinwrobel** [comment]
I do not have any subtitles to choose from the list.
I use Raspberry PI 3B + and KODI 18

**Comment by Gufersil** [comment]
For me it works in some of titles. This weekend, I see that subtitles isn't available on Netflix originals. In some movies or tv shows from other studios,  it works well.
