### ISSUE TITLE
Cannot play any show

### ISSUE THREAD

**Issue by fuxxociety** [CastagnaIT/repository.castagnait#7]
Running LibreELEC 9.0.2 - Kodi "Leia" 18.2
Generic x86_64 platform

Was able to install the Netflix addon, along with all dependancies. 
Upon running the Netflix addon, was prompted for netflix username/pw, and can browse the netflix  library without issue.

Attempting to actually play a show results in the netflix error:
`This title cannot be played because it exceeds the maximum maturity rating set in your parental controls.`

The only show that has worked so far has been the "Life" series.

I have enabled the Parental Controls PIN on Netflix, and have entered the PIN in the addon settings screen.

[kodi-debug-netflixparentalcontrols.log](https://github.com/CastagnaIT/repository.castagnait/files/3513560/kodi-debug-netflixparentalcontrols.log)

**Comment by CastagnaIT** [comment]
this is the addon repository not addon
